app:
    test: Hello from Scrapper Module!
    scheduler:
        interval: 5000
    db_url: jdbc:postgresql://localhost:5432/scrapper
    db_username: postgres
    db_password: password
    database-access-type: jpa

springdoc:
    swagger-ui:
        path: /swagger-ui

github:
    base-url: https://api.github.com

stackoverflow:
    base-url: https://api.stackexchange.com/2.3

bot:
    base-url: http://localhost:8080

server:
    port: 8081

spring:
    jpa:
        openInView: false