app:
  test: Hello from Scrapper Module!
  scheduler:
    interval: 60000 # 1 minute
    check-interval: 900000 # 15 minutes
  db_url: jdbc:postgresql://localhost:5432/scrapper
  db_username: postgres
  db_password: password
  database-access-type: jpa
  use-queue: false
  queue-name: scrapper-queue
  exchange-name: scrapper-exchange

springdoc:
  swagger-ui:
    path: /swagger-ui

github:
  base-url: https://api.github.com

stackoverflow:
  base-url: https://api.stackexchange.com/2.3

bot:
  base-url: http://localhost:9000

server:
  port: 8000

spring:
  jpa:
    openInView: false
    showSql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: password
  application:
    name: scrapper

management:
  server:
    port: 8001
  endpoints:
    web:
      base-path: /
      exposure:
        include: info,health,prometheus
      path-mapping:
        prometheus: metrics
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    tags:
      application: '${spring.application.name}'
