/*
 * This file is generated by jOOQ.
 */

package ru.tinkoff.edu.java.scrapper.domain.jooq;


import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.Chat;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.Link;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.LinkChat;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records.ChatRecord;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records.LinkChatRecord;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records.LinkRecord;
import javax.annotation.processing.Generated;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
        value = {
                "https://www.jooq.org",
                "jOOQ version:3.17.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatRecord> CONSTRAINT_1 =
            Internal.createUniqueKey(Chat.CHAT, DSL.name("CONSTRAINT_1"), new TableField[] {Chat.CHAT.CHAT_ID}, true);
    public static final UniqueKey<LinkRecord> CONSTRAINT_2 =
            Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_2"), new TableField[] {Link.LINK.LINK_ID}, true);
    public static final UniqueKey<LinkRecord> CONSTRAINT_23 =
            Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_23"), new TableField[] {Link.LINK.URL}, true);
    public static final UniqueKey<LinkChatRecord> CONSTRAINT_4 =
            Internal.createUniqueKey(LinkChat.LINK_CHAT, DSL.name("CONSTRAINT_4"),
                    new TableField[] {LinkChat.LINK_CHAT.CHAT_ID, LinkChat.LINK_CHAT.LINK_ID}, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<LinkChatRecord, LinkRecord> CONSTRAINT_47 =
            Internal.createForeignKey(LinkChat.LINK_CHAT, DSL.name("CONSTRAINT_47"),
                    new TableField[] {LinkChat.LINK_CHAT.LINK_ID}, Keys.CONSTRAINT_2,
                    new TableField[] {Link.LINK.LINK_ID}, true);
}
